models/__init__.py
# -*- coding: utf-8 -*-

from content import Content, Tag
from shortcut import Shortcut
from slider import Slider
from footer import Footer, FooterShortcut
from home import Badge, HomeBloc, Home

models/content.py
# -*- coding: utf-8 -*-

from django.utils.timezone import now
from django.utils.html import mark_safe
from django.utils.text import slugify
from django.db import models

from ckeditor.fields import RichTextField

def smart_slugify(string, model, field='slug'):
    slugified = slugify(string)
    kwargs = {
        '{0}__{1}'.format(field, 'istartswith'): slugified,
    }
    conflicts = model.objects.filter(**kwargs).values_list(field, flat=True)
    if conflicts:
        identifier = 0
        base_slug = slugified
        while slugified in conflicts:
            identifier += 1
            slugified = u"{}-{}".format(base_slug, unicode(identifier))
    return slugified

class Tag(models.Model):
    value = models.CharField(max_length=32, verbose_name="Nom") 

    class Meta:
        verbose_name = u'Tag'
        verbose_name_plural = u'Tags'
        ordering = ('value',)

    def __unicode__(self):
        return unicode(self.value)

    def as_span(self, content_type):
        if content_type != None:
            count = content_type.objects.filter(tags=self).distinct().count()
        else:
            count = self.content_set.count()
        return {"badge": mark_safe(u"""<span class="badge">%d</span>""" % count), "label": mark_safe(self.value)}

class Content(models.Model):
    title = models.CharField(max_length=200, verbose_name=u"Titre")
    slug = models.CharField(max_length=200, verbose_name=u"Slug", unique=True)
    image = models.ImageField(verbose_name=u"Image", upload_to="content", null=True, blank=True)
    text = RichTextField(verbose_name=u"Contenu")
    summary = RichTextField(max_length=500, verbose_name=u"Résumé", null=True, blank=True)
    pub_date = models.DateTimeField(verbose_name=u"Publication", default=now)
    tags = models.ManyToManyField(Tag, verbose_name=u"tags")

    def smart_slugify(self):
        return smart_slugify(self.title, Content)
        if conflicts:
            identifier = 0
            base_slug = slugified
            while slugified in conflicts:
                identifier += 1
                slugified = u"{}-{}".format(base_slug, unicode(identifier))
        return slugified

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.slug:
            self.slug = self.smart_slugify()
        super(Content, self).save(force_insert, force_update, using, update_fields)

    def related(self):
        return type(self).objects.filter(tags__in=self.tags.all()).distinct().exclude(pk=self.pk)[:5]

    def related_tags(self):
        return [reduce(lambda x,y: dict(x, **y), ({"pk": tag.pk, }, tag.as_span(type(self)))) for tag in self.tags.all()]

    def all_tags(self):
        return [reduce(lambda x,y: dict(x, **y), ({"pk": tag.pk, }, tag.as_span(type(self)))) for tag in Tag.objects.filter(content__isnull=False).distinct()]

    class Meta:
        ordering = ('-pub_date',)

    def __unicode__(self):
        return unicode(self.title)

models/footer.py
# -*- coding: utf-8 -*-

from django.db import models

from ckeditor.fields import RichTextField

from balcony.models import Shortcut

class Footer(models.Model):
    title = models.CharField(max_length=200, verbose_name=u"Title", null=True, blank=True)
    text = RichTextField(verbose_name=u"Texte", null=True, blank=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u'Footer'
        verbose_name_plural = u'Footers'
    
class FooterShortcut(Shortcut):
    footer = models.ForeignKey(Footer, related_name="shortcuts")
    

models/home.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.timezone import now

from colorfield.fields import ColorField

from balcony.models import Shortcut, Slider, Footer

class HomeBloc(Shortcut):
    class Meta:
        verbose_name = u'Argumentary'
        verbose_name_plural = u'Argumentaries'
        ordering = ('date_added',)

class Badge(Shortcut):
    pass


class Home(models.Model):
    logo = models.ImageField(verbose_name=u"Image", upload_to="shortcut", null=True, blank=True)

    sliders = models.BooleanField(default=True, verbose_name=u"Show sliders")
    badges = models.BooleanField(default=True, verbose_name=u"Show badges")
    homeblocs = models.BooleanField(default=True, verbose_name=u"Show argumentaries")

    header_color = ColorField(default="#3264AD", verbose_name=u"Background color")
    sliders_color = ColorField(default="#3264AD", verbose_name=u"Background color")
    badges_color = ColorField(default="#3264AD", verbose_name=u"Background color")
    homeblocs_color = ColorField(default="#EEEEEE", verbose_name=u"Background color")

    def get_sliders(self):
        return Slider.objects.filter(active=True).order_by('-date_added')

    def get_badges(self):
        return Badge.objects.filter(active=True).order_by('-date_added')

    def get_homeblocs(self):
        return HomeBloc.objects.filter(active=True).order_by('-date_added')

    def get_footers(self):
        return Footer.objects.all()[:3]


    class Meta:
        verbose_name = u"Global settings"
        verbose_name_plural = u"Global settings"

models/shortcut.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.timezone import now

from ckeditor.fields import RichTextField

from mezzanine.pages.models import Page


class Shortcut(models.Model):
    page = models.ForeignKey(Page, related_name="shortcut", verbose_name=u"Page", null=True, blank=True)
    title = models.CharField(max_length=200, verbose_name=u"Titre", null=True, blank=True)
    image = models.ImageField(verbose_name=u"Image", upload_to="shortcut", null=True, blank=True)
    text = RichTextField(verbose_name=u"Texte", null=True, blank=True)
    url = models.CharField(max_length=200, verbose_name=u"Url", help_text=u"Lien vers lequel doit pointer le bouton (hyperlien ou balise)", null=True,
                          blank=True)
    button_text = models.CharField(max_length=50, verbose_name=u"Texte du bouton", null=True, blank=True)
    active = models.BooleanField(verbose_name=u"Actif", help_text=u"Défini si l'élément doit s'afficher ou non",
                                 default=True)
    date_added = models.DateTimeField(verbose_name=u"Date d'ajout", default=now)

    class Meta:
        verbose_name = u'Raccourci'
        verbose_name_plural = u'Raccourcis'
        ordering = ('-date_added',)
    
    def __unicode__(self):
        return unicode(self.title)

models/slider.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.timezone import now

from balcony.models import Shortcut


class Slider(Shortcut):
    class Meta:
        verbose_name = u'Slider'
        verbose_name_plural = u'Sliders'
        ordering = ('-date_added',)

admin/__init__.py
# -*- coding: utf-8 -*-

from slider import SliderAdmin
from home import HomeBlocAdmin
from footer import FooterAdmin

views.py
from django.shortcuts import render

# Create your views here.

templates/accounts/account_form.html
{% extends "base.html" %}
{% load i18n mezzanine_tags %}

{% block meta_title %}{{ title }}{% endblock %}
{% block title %}{{ title }}{% endblock %}
{% block body_id %}account{% endblock %}

{% block breadcrumb_menu %}
{{ block.super }}
<li>{{ title }}</li>
{% endblock %}

{% block main %}

{% errors_for form %}

<form method="post"{% if form.is_multipart %} enctype="multipart/form-data"{% endif %} role="form" class="center">
    <fieldset class="registration-form">
    
    {% fields_for form %}
   
    <div class="form-group">
                    <button type="submit" class="btn btn-success btn-md btn-block">{{ title }}</button>
                     {% block account_form_actions %}
        
        {% endblock %}
                </div>
    </fieldset>
</form>



{% endblock %}

templates/accounts/account_login.html
{% extends "accounts/account_form.html" %}
{% load i18n future %}

{% block main %}
<section id="registration" class="container">
{% if request.user.is_authenticated %}
    <p>{% trans "You're already logged in. If you'd like to log in as a different user, you'll need to log out first." %}</p>
{% else %}
    {{ block.super }}
    {% url "signup" as signup_url %}
    <p>{% blocktrans with request.GET.next as next %}If you don't have an account you can <a href="{{ signup_url }}?next={{ next }}">sign up</a> for one now.{% endblocktrans %}</p>
    {% url "mezzanine_password_reset" as password_reset_url %}
    {% url "profile_update" as profile_update_url %}
    {% blocktrans %}<p>You can also <a href="{{ password_reset_url }}?next={{ profile_update_url }}">reset your password</a> if you've forgotten it.</p>{% endblocktrans %}</p>
{% endif %}
</section>
{% endblock %}

templates/accounts/account_password_reset.html
{% extends "accounts/account_form.html" %}
{% load i18n %}

{% block main %}
{{ block.super }}
<p>{% trans "Enter your username or email address and you'll receive an email with a link you need to click, in order to log in and change your password." %}</p>
{% endblock %}

templates/accounts/account_profile.html
{% extends "base.html" %}
{% load i18n future mezzanine_tags accounts_tags %}

{% block meta_title %}{{ profile_user|username_or:"get_full_name" }}{% endblock %}
{% block title %}{{ profile_user|username_or:"get_full_name" }}{% endblock %}
{% block body_id %}account{% endblock %}

{% block breadcrumb_menu %}
{{ block.super }}
<li>{{ profile_user|username_or:"get_full_name" }}</li>
{% endblock %}

{% block main %}
<div class="row">
<div class="profile-image col-md-3">
    <img class="img-thumbnail" src="{% gravatar_url profile_user.email 128 %}">
    {% if profile_user == request.user %}
    <br><a class="btn btn-primary" href="{% url "profile_update" %}">{% trans "Update profile" %}</a>
    {% endif %}
</div>
<div class="profile-content col-md-9">
    <h2>{{ profile_user.get_full_name }}</h2>
    {% for field, value in profile_user|profile_fields %}
    <h3>{{ field }}</h3>
    <p>{{ value|linebreaksbr }}</p>
    {% endfor %}
</div>
</div>
{% endblock %}

templates/accounts/account_profile_update.html
{% extends "accounts/account_form.html" %}

templates/accounts/account_signup.html
{% extends "accounts/account_form.html" %}
{% load i18n %}

{% block main %}
<section id="registration" class="container">
{% if request.user.is_authenticated %}
    <p>{% trans "You're already logged in. If you'd like to create a new account, you'll need to log out first." %}</p>
{% else %}
    {{ block.super }}
    {% if settings.ACCOUNTS_APPROVAL_REQUIRED %}
    <p>{% trans "After signing up, your account will be reviewed for approval. You'll receive an email when your account is activated." %}</p>
    {% elif settings.ACCOUNTS_VERIFICATION_REQUIRED %}
    <p>{% trans "After signing up, you'll receive an email with a link you need to click, in order to activate your account." %}</p>
    {% endif %}
{% endif %}
</section>
{% endblock %}

templates/accounts/includes/user_panel.html
{% load i18n future mezzanine_tags accounts_tags %}

{% if request.user.is_authenticated %}
    <li>
    
    {% url "profile" request.user.username as profile_url %}
    {% if profile_url %}
        <a href="{{ profile_url }}">{{ request.user|username_or:"email" }}</a>
    </li>
    <li>
        <a href="{% url "profile_update" %}" class="">
 <i class="icon-edit"></i> {% trans "Update profile" %}</a>
            
    {% else %}
        <a href="{% url "profile_update" %}">{{ request.user|username_or:"email" }}</a>
       
    
    {% endif %}
     </li>
    <li>
    <a href="{% url "logout" %}?next={{ request.path }}" class="">
         <i class="icon-signout"></i> {% trans "Log out" %}</a>
        </li>
{% else %}
<li>
    <a href="{% url "login" %}?next={{ request.path }}" class="">
        <i class="icon-signin"></i> {% trans "Log in" %}</a>
   
    <a href="{% url "signup" %}?next={{ request.path }}" class="">
         <i class="icon-edit"></i> {% trans "Sign up" %}</a>
        </li>
{% endif %}

templates/accounts/includes/user_panel_nav.html
{% load i18n future mezzanine_tags accounts_tags %}

<div class="navbar-right navbar-account-controls">
    {% if request.user.is_authenticated %}
    {% url "profile" request.user.username as profile_url %}
    {% if not profile_url %}{% url "profile_update" as profile_url %}{% endif %}
    <p class="navbar-text">
        <a class="navbar-link" href="{{ profile_url }}">
            <span class="glyphicon glyphicon-user"></span> {{ request.user|username_or:"email" }}</a></p>
    <a href="{% url "logout" %}?next={{ request.path }}" class="btn btn-default navbar-btn">
        <span class="glyphicon glyphicon-log-out"></span> {% trans "Log out" %}</a>
    {% else %}
    <a href="{% url "login" %}?next={{ request.path }}" class="btn btn-default navbar-btn">
        <span class="glyphicon glyphicon-log-in"></span> {% trans "Log in" %}</a>
    <a href="{% url "signup" %}?next={{ request.path }}" class="btn btn-default navbar-btn">
        <span class="glyphicon glyphicon-edit"></span> {% trans "Sign up" %}</a>
    {% endif %}
</div>

templates/base.html
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
  {% load pages_tags mezzanine_tags i18n future static staticfiles balcony_tags %}
  
  {% balcony_settings as balcony %}
  {% get_media_prefix as MEDIA_PREFIX %}

  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <title>{% block meta_title %}{% endblock %}{% if settings.SITE_TITLE %} | {{ settings.SITE_TITLE }}{% endif %}</title>
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}">
    
    {% ifinstalled mezzanine.blog %}
    <link rel="alternate" type="application/rss+xml" title="RSS" href="{% url "blog_post_feed" "rss" %}">
    <link rel="alternate" type="application/atom+xml" title="Atom" href="{% url "blog_post_feed" "atom" %}">
    {% endifinstalled %}
    
    {% compress css %}
    
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/mezzanine.css" %}">
    
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet">
    <link href="{% static "css/prettyPhoto.css" %}" rel="stylesheet">
    <link href="{% static "css/animate.css" %}" rel="stylesheet">
    <link href="{% static "css/main.css" %}" rel="stylesheet">
    
    {% if LANGUAGE_BIDI %}
    <link rel="stylesheet" href="{% static "css/rtl.css" %}">
    {% endif %}
    {% ifinstalled cartridge.shop %}
    <link rel="stylesheet" href="{% static "css/cartridge.css" %}">
    {% if LANGUAGE_BIDI %}
    <link rel="stylesheet" href="{% static "css/cartridge.rtl.css" %}">
    {% endif %}
    {% endifinstalled %}
    {% block extra_css %}{% endblock %}
    {% endcompress %}
    <!--[if lt IE 9]>
	<script src="{% static "js/html5shiv.js" %}"></script>
	<script src="{% static "js/respond.min.js" %}"></script>
	<![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">

    {% compress js %}
    <script src="{% static "mezzanine/js/"|add:settings.JQUERY_FILENAME %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/bootstrap-extras.js" %}"></script>
    {% block extra_js %}{% endblock %}
    {% include "includes/footer_scripts.html" %}
    {% endcompress %}
    <!--[if lt IE 9]>
	<script src="{% static "js/html5shiv.js" %}"></script>
	<script src="{% static "js/respond.min.js" %}"></script>
	<![endif]-->

    {% block extra_head %}{% endblock %}
  </head>

  <body id="{% block body_id %}body{% endblock %}">

    <header class="navbar navbar-inverse navbar-fixed-top" style="background-color:{{balcony.header_color}};" role="banner">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
	  {% if balcony.logo %}
	  <a class="navbar-brand" href="/">
	    <img src="{{ MEDIA_PREFIX }}{{ balcony.logo }}" class="img-responsive" />
	  </a>
	  {% else %}
            {% if settings.SITE_TITLE %}
	    <a class="navbar-brand" href="/">
	      {{ settings.SITE_TITLE }}
	    </a>
	    {% endif %}
	  {% endif %}
	  {% if settings.SITE_TAGLINE %}<p class="navbar-text visible-lg">{{ settings.SITE_TAGLINE }}</p>{% endif %}
        </div>
        <div class="collapse navbar-collapse">
          {% page_menu "pages/menus/dropdown.html" %}
	</div>
      </div>
    </header><!--/header-->


    <div class="container">

      {% nevercache %}
      {% if messages %}
      <div class="messages">
	{% for message in messages %}
	<div class="alert alert-dismissable alert-{{ message.tags }}" data-alert="alert">
	  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	  {{ message }}
	</div>
	{% endfor %}
      </div>
      {% endif %}
      {% endnevercache %}
    </div>

    {% block top %}
    <section class="emerald" style="background-color:{{balcony.sliders_color}};" id="title">
      <div class="container">
        <div class="row">
          <div class="col-sm-6">
            <h1>{% block title %}{% endblock %}</h1>
            
          </div>
          <div class="col-sm-6">
            <ul class="breadcrumb pull-right">
              {% spaceless %}
	      {% block breadcrumb_menu %}{% page_menu "pages/menus/breadcrumb.html" %}{% endblock %}
	      {% endspaceless %}
            </ul>
          </div>
        </div>
      </div>
    </section>
    {% endblock %}
    
    {% block left_panel %}
    {% endblock %}

    {% block main %}{% endblock %}
    
    <section id="bottom" class="wet-asphalt">
      <div class="container">
	{% page_menu "pages/menus/footer.html" %}
      </div>
    </section>
    <footer id="footer" class="midnight-blue">
      <div class="container">
	
	
	<div class="row">
	  <div class="col-sm-6">
            {% if settings.SITE_TITLE %}© {{ settings.SITE_TITLE }} {% now "Y" %} {% endif %}
	  </div>
	  <div class="col-sm-6">
	    <ul class="pull-right">
              <li><a id="gototop" class="gototop" href="#"><i class="icon-chevron-up"></i></a></li>
	    </ul>
	  </div>
	  
	</div>
      </div>
    </footer>
    
    <script src="{% static "js/jquery.prettyPhoto.js" %}"></script>
    <script src="{% static "js/jquery.isotope.min.js" %}"></script>
    <script src="{% static "js/main.js" %}"></script>
  </body>
</html>

templates/blog/blog_post_detail.html
{% extends "blog/blog_post_list.html" %}
{% load mezzanine_tags comment_tags keyword_tags rating_tags i18n future disqus_tags %}

{% block meta_title %}{{ blog_post.meta_title }}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for blog_post as tags %}
{% for tag in tags %}{% if not forloop.first %}, {% endif %}{{ tag }}{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ blog_post.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% editable blog_post.title %}{{ blog_post.title }}{% endeditable %}
{% endblock %}

{% block breadcrumb_menu %}
{{ block.super }}
<li class="active">{{ blog_post.title }}</li>
{% endblock %}

{% block main %}
<section id="blog" class="container">
	<div class="row">
		<div class="col-sm-8">
			<div class="blog">
			<div class="blog-item">
		 {% if settings.BLOG_USE_FEATURED_IMAGE and blog_post.featured_image %}
			{% block blog_post_list_post_featured_image %}
			<a href="{{ blog_post.get_absolute_url }}">
				<img width="100%" class="img-responsive img-blog" src="{{ MEDIA_URL }}{{blog_post.featured_image }}">
			</a>
			{% endblock %}
			{% endif %}
		<div class="blog-content">
			
	{% block blog_post_list_post_title %}
		
	
	{% endblock %}
{% block blog_post_list_post_metainfo %}
{% editable blog_post.publish_date %}
                   <div class="entry-meta">
                                <span><i class="icon-user"></i> {% with blog_post.user as author %}
								<a href="{% url "blog_post_list_author" author %}">{{ author.get_full_name|default:author.username }}</a>
								{% endwith %}
								</span>
                                <span><i class="icon-folder-close"></i>
                                {% with blog_post.categories.all as categories %}
								{% if categories %}
								{% trans "in" %}
								{% for category in categories %}
								<a href="{% url "blog_post_list_category" category.slug %}">{{ category }}</a>{% if not forloop.last %}, {% endif %}
								{% endfor %}
								{% endif %}
								{% endwith %}
                                
                                </span>
                                <span><i class="icon-calendar"></i> {% blocktrans with sometime=blog_post.publish_date|timesince %}{{ sometime }} ago{% endblocktrans %}</span>
                                <span><i class="icon-comment"></i> 
                                {% if blog_post.allow_comments %}
									
									{% if settings.COMMENTS_DISQUS_SHORTNAME %}
									<a href="{{ blog_post.get_absolute_url }}#disqus_thread"
										data-disqus-identifier="{% disqus_id_for blog_post %}">
										{% trans "Comments" %}
									</a>
									{% else %}
									<a href="{{ blog_post.get_absolute_url }}#comments">
										{% blocktrans count comments_count=blog_post.comments_count %}{{ comments_count }} comment{% plural %}{{ comments_count }} comments{% endblocktrans %}
									</a>
									{% endif %}
									{% endif %}
																
                                </span>
                            </div>

{% endeditable %}
{% endblock %}



{% block blog_post_list_post_content %}
{% editable blog_post.content %}
{{ blog_post.description_from_content|safe }}
{% endeditable %}
{% endblock %}

 <a href="{{ blog_post.get_absolute_url }}"  class="btn btn-default">{% trans "read more" %} <i class="icon-angle-right"> </i></a>
{% block blog_post_list_post_links %}
{% keywords_for blog_post as tags %}
    {% if tags %}
<div class="tags">
  <i class="icon-tags"></i> {% trans "Tags" %}:
    {% spaceless %}
    {% for tag in tags %} 

  <a href="{% url "blog_post_list_tag" tag.slug %}" class="btn btn-xs btn-primary">{{ tag }}</a>
  {% endfor %}
    {% endspaceless %}
</div>
{% endif %}
{% block blog_post_detail_comments %}
{% if blog_post.allow_comments %}{% comments_for blog_post %}{% endif %}
{% endblock %}

{% endblock %}

</div>
</div>
</div>
</div>
</div>
</section>
{% endblock %}
{% block blog_post_detail_rating %}
<div class="panel panel-default rating">
    <div class="panel-body">
    {% rating_for blog_post %}
    </div>
</div>
{% endblock %}

{% block blog_post_detail_sharebuttons %}
{% set_short_url_for blog_post %}
<a class="btn btn-sm share-twitter" target="_blank" href="http://twitter.com/home?status={{ blog_post.short_url|urlencode }}%20{{ blog_post.title|urlencode }}">{% trans "Share on Twitter" %}</a>
<a class="btn btn-sm share-facebook" target="_blank" href="http://facebook.com/sharer.php?u={{ request.build_absolute_uri }}&amp;t={{ blog_post.title|urlencode }}">{% trans "Share on Facebook" %}</a>
{% endblock %}

{% block blog_post_previous_next %}
<ul class="pager">
{% with blog_post.get_previous_by_publish_date as previous %}
{% if previous %}
<li class="previous">
    <a href="{{ previous.get_absolute_url }}">&larr; {{ previous }}</a>
</li>
{% endif %}
{% endwith %}
{% with blog_post.get_next_by_publish_date as next %}
{% if next %}
<li class="next">
    <a href="{{ next.get_absolute_url }}">{{ next }} &rarr;</a>
</li>
{% endif %}
{% endwith %}
</ul>
{% endblock %}

{% block blog_post_detail_related_posts %}
{% if blog_post.related_posts.all %}
<div id="related-posts">
<h3>{% trans 'Related posts' %}</h3>
<ul class="list-unstyled">
{% for post in blog_post.related_posts.all %}
     <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
{% endfor %}
</ul>
</div>
{% endif %}

{% endblock %}

templates/generic/comments.html
{% extends "base.html" %}

{% load mezzanine_tags comment_tags keyword_tags %}

{% block meta_title %}{{ obj }}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for obj as tags %}
{% for tag in tags %}{% if not forloop.first %}, {% endif %}{{ tag }}{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ obj.description }}
{% endmetablock %}{% endblock %}

{% block main %}
{% comments_for obj %}
{% endblock %}

templates/generic/includes/comment_form.html
{% load i18n mezzanine_tags comment_tags %}

<form method="post" id="contactform" action="{{ comment_url }}#comment" class="form-horizontal" role="form">
   {% csrf_token %}
	{% for hidden in comment_form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
	
	<div class="form-group">
		<div class="col-sm-4">
			<input type="text" value="{{comment_form.name.value}}" name="name" id="id_name"  placeholder="* Enter your full name" class="form-control" >
		</div>
		<div class="col-sm-4">
			<input type="email" value="{{comment_form.email.value}}" name="email" id="id_email" placeholder="* Enter your email address" class="form-control">
		</div>
		<div class="col-sm-4">
		   <input type="url" value="" name="{{comment_form.url.value}}" id="id_url" placeholder="Enter your webiste" class="form-control">
		</div> 
    </div>
	<div class="form-group">
		<div class="col-sm-12">
			
			<textarea rows="8" name="comment" id="id_comment"  class="form-control" placeholder="* Enter Comment here..."></textarea>
		</div>
    </div>
	<button class="btn btn-danger btn-lg" type="submit">Submit Comment</button>
</form>

templates/generic/includes/disqus_sso.html
<script>
var disqus_config = function () {
    this.page.remote_auth_s3 = '{{ sso_data }}';
    this.page.api_key = '{{ public_key }}';
}
</script>